
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: service-feign66
ribbon:
  eureka:
    enabled: true

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8086
feign:
  hystrix:
    enabled: true

